config/routes.rb
Muxu::Application.routes.draw do
  resources :friendships

  get "home/index"

  get "comments/create"

  resources :objs do
  	resources :comments
  end

  get "admin/login"
  get "admin/index"
  post "admin/login"

  get "admin/logout"

  resources :users
  
  get "search/index"
  get "search/result"
  post "search/result"

  root :to => "home#index"

end

app/models/user.rb
# coding: utf-8
require 'digest/sha1'

class User < ActiveRecord::Base

include Paperclip
	has_attached_file :photo, :styles =>{:medium=>"160x160>", :thumb =>"80x80>"}
	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than =>3.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png','image/gif']

	has_many :comments
	has_many :objs, :through=>:comments
	has_many :friendships
	has_many :friends, :through=>:friendships
	
	validates_presence_of :nickname
	validates_presence_of :email
	validates_uniqueness_of :nickname
	validates_uniqueness_of :email
	
	attr_accessor :password_confirmation
	validates_confirmation_of :password
	
	validate :password_non_blank

def self.authenticate(email, password)
    user = self.find_by_email(email)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.hashed_password != expected_password
        user = nil
      end
    end
    user
  end
  
  
  # 'password' is a virtual attribute
  
  def password
    @password
  end
  
  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
  end
  
  

private

  def password_non_blank
    errors.add(:password, "密码为空") if hashed_password.blank?
  end

  
  
  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
  
  
  
  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end
		
	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
      format.json  { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    if @current_user
    	@friendship_with_current= Friendship.find_by_sql("select * from friendships where user_id=1 and friend_id=2")
    	else
    	@friendship_with_current = nil
	end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        flash[:notice] = "User #{@user.name} was successfully created."
		format.html { redirect_to(:action=>'index' ) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = "User #{@user.name} was successfully updated."
        format.html { redirect_to(:action=>'index' ) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form _origin.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :born %><br />
    <%= f.date_select :born %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
 
  <div>
<%= f.label :password, 'Password' %>:
<%= f.password_field :password, :size => 40 %>
</div>
<div>
<%= f.label :password_confirmation, 'Confirm' %>:
<%= f.password_field :password_confirmation, :size => 40 %>
</div>

  
  
  
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div id="main" class="container_12 no_bg">
	<div id="signup" class="grid_10 prefix_1">
		<div>
		<h1>注册</h1>
		
		</div>

	<table>
		<tbody>
		<tr>
			<th><label for="name">用户名</label></th>
			<td> <%= f.text_field :nickname %></td>
			<td><p>已注册用户，请<a href="">登录</a></p></td>
		</tr>
		<tr>
			<th><label for="email">邮箱</label></th>
			<td><%= f.text_field :email %></td>
			<td></td>
		</tr>
		<tr>
			<th><label for="password">密码</label></th>
			<td><%= f.password_field :password %></td>
			<td></td>
		</tr>
		<tr>
			<th><label for="password_conform">确认密码</label></th>
			<td><%= f.password_field :password_confirmation %></td>
			<td></td>
		</tr>
		<tr>
			<th></th>
			<td><span><%= f.submit "注册" %></td>
			<td></td>
		</tr>
		</tbody>
	</table>

<% end %>

app/views/users/_form_setting.html.erb
<%= form_for @user,:html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="main" class="container_12 no_bg">
	<div id="setting" class="grid_10 prefix_1">
		<div>
		<h1>个人设置</h1>
		<div id="settingmenu"><span><a href="">账户信息</a></span></div>
		</div>
		
			<table>
				<tbody>
				<tr>
					<th><label for="name">真实姓名</label></th>
					<td><%= f.text_field :name %></td>
				</tr>
				<tr>
					<th><label for="nickname">用户名</label></th>
					<td><%= f.text_field :nickname %></td>
				</tr>
				
				<tr>
					<th><label for="photo">个人头像</label></th>
					<td>
					<div>
						<%= image_tag @user.photo.url(:thumb)%>
					</div>
					<div><%= f.file_field :photo %></div></td>
					
				</tr>
				
				
				<tr>
					<th></th>
					<td><span><%= f.submit "保存设置"%></td>
					<td></td>
				</tr>
				</tbody>
			</table>
		
		
		
		
	</div>
	<div class="clear"></div>
	
</div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form_setting' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Born</th>
    <th>Email</th>
    <th>Nickname</th>
    <th>Mobile</th>
    <th>City</th>
    <th>Address</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.gender %></td>
    <td><%= user.born %></td>
    <td><%= user.email %></td>
    <td><%= user.nickname %></td>
    <td><%= user.mobile %></td>
    <td><%= user.city %></td>
    <td><%= user.address %></td>
    <td><%= user.image %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div id="main" class="container_12 no_bg">
	<div id="page_content">
		<div class="user_info grid_8">
			<a href="" class="grid_2"><%= image_tag @user.photo.url(:thumb)%></a>
			<div class="grid_6 alpha omega">
				<p><%=  @user.nickname%></p><p><%= @friendship_with_current%></p>
				<% if @friendship_with_current %>
				<p><%= link_to "取消关注", friendships_path(:friend_id=>@user),:method =>:delete, :class => "button green"%></p>
				<%else%>
				<p><%= link_to "关注TA", friendships_path(:friend_id=>@user),:method =>:post, :class => "button green"%></p>
				<%end%>
			</div>
		</div>
		<div class="clear"></div>
		<div id="nav_col" class="grid_2">		
		</div>
		<div id="activity_col" class="grid_7 alpha">
		<h3>最新动态</h3>
		<div class="feed_items">
			<% @user.comments.each do |comm| %>
			<div class="feed_item">
			<div class="item_header">
				<div class="user_image" style="float:left;">
					<a href=""><%= image_tag @user.photo.url(:thumb), :size=> "30x30"%></a>
				</div>
				<div class="feed_meta grid_6 omega">
					<p class="author_action"><%= @user.name%>在<%= link_to comm.obj.name, obj_path(comm.obj)%>签到</p>
					<p class="feed_actions"><span><%= time_ago_in_words(comm.created_at)%></span><a href="">添加回复</a></p>
				</div>
				<div class="feed_reaction"></div>
			</div>
			<div class="item_content">
				<div class="checkin_image" style="float:left"><%= image_tag comm.obj.image.url(:thumb), :size=> "50x75"%></div>
				<div class="checkin_body grid_5">在<%= link_to comm.obj.name, obj_path(comm.obj)%>签到</div>
			</div>
			<div class="replay_content"></div>
			<div class="replay_form"></div>
			<div class="clear"></div>
			</div>
			<% end %>
		</div>
		</div>
		<div id="social_col" class="grid_3">
			<div class="section"> 
				<h4>TA的积分</h4>
			</div>
			<div class="section"> 
				<h4>TA的勋章</h4>
			</div>
			<div class="section"> 
				<h4>邀请好友</h4>
			</div>
			
		</div>
		<div class="clear"></div>
	</div>
	
	
</div>