config/routes.rb
Muxu::Application.routes.draw do
  resources :friendships

  get "home/index"

  get "comments/create"

  resources :objs do
  	resources :comments
  end

  get "admin/login"
  get "admin/index"
  post "admin/login"

  get "admin/logout"

  resources :users
  
  get "search/index"
  get "search/result"
  post "search/result"

  root :to => "home#index"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name =>"User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = current_user.friendships.build(:friend_id=>params[:friend_id])

    respond_to do |format|
      if @friendship.save
        flash[:notice] = "add friend successfully!" 
        redirect_to root_path
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friendship.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to(friendships_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :friend %><br />
    <%= f.text_field :friend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th>User</th>
    <th>Friend</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= friendship.user %></td>
    <td><%= friendship.friend %></td>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @friendship.user %>
</p>

<p>
  <b>Friend:</b>
  <%= @friendship.friend %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>