config/routes.rb
Muxu::Application.routes.draw do
  resources :friendships

  get "home/index"

  get "comments/create"

  resources :objs do
  	resources :comments
  end

  get "admin/login"
  get "admin/index"
  post "admin/login"

  get "admin/logout"

  resources :users
  
  get "search/index"
  get "search/result"
  post "search/result"

  root :to => "home#index"

end

app/models/obj.rb
class Obj < ActiveRecord::Base
	include Paperclip
	
	has_many :comments
	has_many :users, :through=>:comments
	
	validates_presence_of :name
	has_attached_file :image, :styles =>{:medium=>"140x160>", :thumb =>"100x147>"}
	validates_attachment_presence :image
	validates_attachment_size :image, :less_than =>3.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png','image/gif']
	
	
end

app/controllers/objs_controller.rb
class ObjsController < ApplicationController
  # GET /objs
  # GET /objs.xml
  def index
    @objs = Obj.all
   

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @objs }
    end
  end

  # GET /objs/1
  # GET /objs/1.xml
  def show
    @obj = Obj.find(params[:id])
	@current_user = User.find_by_id(session[:user_id]) if session[:user_id]
    session[:custom_uri]= obj_path(@obj)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @obj }
    end
  end

  # GET /objs/new
  # GET /objs/new.xml
  def new
    @obj = Obj.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @obj }
    end
  end

  # GET /objs/1/edit
  def edit
    @obj = Obj.find(params[:id])
  end

  # POST /objs
  # POST /objs.xml
  def create
    @obj = Obj.new(params[:obj])

    respond_to do |format|
      if @obj.save
        format.html { redirect_to(@obj, :notice => 'Obj was successfully created.') }
        format.xml  { render :xml => @obj, :status => :created, :location => @obj }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @obj.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /objs/1
  # PUT /objs/1.xml
  def update
    @obj = Obj.find(params[:id])

    respond_to do |format|
      if @obj.update_attributes(params[:obj])
        format.html { redirect_to(@obj, :notice => 'Obj was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @obj.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /objs/1
  # DELETE /objs/1.xml
  def destroy
    @obj = Obj.find(params[:id])
    @obj.destroy

    respond_to do |format|
      format.html { redirect_to(objs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/objs_helper.rb
module ObjsHelper
end

app/views/objs/_form.html.erb
<%= form_for @obj, :html => { :multipart => true} do |f| %>
  <% if @obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@obj.errors.count, "error") %> prohibited this obj from being saved:</h2>

      <ul>
      <% @obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cat %><br />
    <%= f.text_field :cat %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
    <div class="field">
    <%= f.label :图片上传 %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objs/edit.html.erb
<h1>Editing obj</h1>

<%= render 'form' %>

<%= link_to 'Show', @obj %> |
<%= link_to 'Back', objs_path %>

app/views/objs/index.html.erb
<h1>Listing objs</h1>


<table>
  <tr>
    <th>Name</th>
    <th>Cat</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @objs.each do |obj| %>
    <%obj.comments.each do |comment|%>
     <%= comment.user.nickname%>
    <%end%>
  <tr>
    <td><%= obj.name %></td>
    <td><%= obj.cat %></td>
    <td><%= obj.content %></td>
    <td><%= link_to 'Show', obj %></td>
    <td><%= link_to 'Edit', edit_obj_path(obj) %></td>
    <td><%= link_to 'Destroy', obj, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<% @objs = nil%>
<br />

<%= link_to 'New Obj', new_obj_path %>

app/views/objs/new.html.erb
<h1>New obj</h1>

<%= render 'form' %>

<%= link_to 'Back', objs_path %>

app/views/objs/show.html.erb
<div id="main" class="container_12 no_bg">
	<div id="page_content">
		<div class="entity_header grid_8">
			<a href="" class="grid_2">  <%= image_tag @obj.image.url(:thumb)%></a>
			<div class="grid_6 alpha omega">
				<p><%= @obj.name %>&nbsp;(&nbsp;<%= @obj.cat %>&nbsp;) </p> 
				<p><a href="#" class="button green">关注</a>
				<%= link_to 'Edit', edit_obj_path(@obj) %> |
                <%= link_to 'Back', objs_path %></p>
			</div>
		</div>
		<div class="clear"></div>
		<div id="nav_col" class="grid_2">	
			<ul class="grid_2 alpha">
			<li><a href="">所有动态</a></li>
			<li><a href="">好友的动态</a></li>			
		</ul>
		</div>
		<div id="activity_col" class="grid_7 alpha">
		<h3>最新动态</h3>

		<div class="feed_items">
		
	
			<% @obj.comments.each do |comm|%>
	
			
			<div class="feed_item">
			<div class="item_header">
				<div class="user_image" style="float:left;">
					<a href=""><img src="" width="30px" height="30px"/></a>
				</div>
				<div class="feed_meta grid_6 omega">
					<p class="author_action"><%= link_to comm.user.nickname,user_path(comm.user) %>在<%= link_to comm.obj.name, obj_path(comm.obj)%>签到</p>
					<p class="feed_actions"><span><%= time_ago_in_words(comm.created_at)%></span><a href="">添加回复</a></p>
				</div>
				<div class="feed_reaction"></div>
			</div>
			<div class="item_content">
				<div class="checkin_image" style="float:left"><img src="" width="50px" height="75px"/></div>
				<div class="checkin_body grid_5">在<a href="item_page.html">big bang 第四季</a>签到</div>
			</div>
			<div class="replay_content"></div>
			<div class="replay_form"></div>
			<div class="clear"></div>
			</div>
						
			<% end %>
			

		</div>
		</div>
		<div id="social_col" class="grid_3">
			<div class="section"> 
				<h4>你的状态</h4>
			</div>
			<div class="section"> 
				<h4>积分榜</h4>
			</div>
			<div class="section"> 
				<h4>看过的好友</h4>
			</div>
			
		</div>
		<div class="clear"></div>
	</div>
	
	
</div>